name: zinc

params_train: 
  _target_: dataloader.tg_datasets.get_zinc_dataset
  path: ${DATA_DIR}/datasets/lrgb
  use_distance_masks: ${model.use_distance_masks}
  precomputed_masks_path: ./data/precomputed_dist_masks/zinc/split=train_n=${.n_samples_max}_k=8.pt
  split: train
  n_samples_max: 12000

params_test: 
  _target_: dataloader.tg_datasets.get_zinc_dataset
  path: ${DATA_DIR}/datasets/lrgb
  use_distance_masks: ${model.use_distance_masks}
  precomputed_masks_path: ./data/precomputed_dist_masks/zinc/split=val_n=${.n_samples_max}_k=8.pt
  split: val
  n_samples_max: 2000

  
feature_dim: 1
edge_dim: 1

node_classes: 28
edge_classes: 4

classes: 1 # quantities to regress in this case
embed_type: embedding
