defaults: 
  - _self_
  - model: GREDMamba
  - dataset: peptides-struct
  - loss: mse
  - evaluator: loss_evaluator
  
seed: 0
num_epochs: 50
log_frequency: 10
evaluate_frequency: 1

print: True
use_wandb: True
log_model: True

num_workers: 4
num_threads: 4

project_name: SeqForGraphs

DATA_DIR: /home/${oc.env:USER}/data/${project_name}

wandb:
  tags: []
  project: ${project_name}
  group: 'pept-base6'
  name: '${model.name}_${dataset.name}_${now:%Y-%m-%d_%H-%M-%S}'

workdir: 
  root: ${DATA_DIR}
  name: 'models/${model.name}/${wandb.group}/${now:%Y-%m-%d_%H-%M-%S}'
  checkpoint_path: '${workdir.root}/${workdir.name}/ckpt.pth'

hydra:
  run:
    dir: ${DATA_DIR}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
